# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-19 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='music_link',
            field=models.CharField(default='', max_length=300),
        ),
    ]
